apps/calc/urls.py
from django.urls import path

from calc.views import (
    calcs_list, adding_calc, calc_details, crud_furniture, crud_detail, leave_comment, adding_new_furniture
)

# app_name = "calc"
urlpatterns = [
    path('calcs/', calcs_list, name='calc_list'),
    path('adding_calc/', adding_calc, name='adding_calc'),
    path('calc/<int:calc_id>/', calc_details, name='calc_details'),

    path('crud_detail/', crud_detail, name='crud_detail'),
    path('crud_furniture/', crud_furniture, name='crud_furniture'),
    path('leave_comment/<int:calc_id>/', leave_comment, name='leave_comment'),
    path('adding_new_furniture/<int:calc_id>/', adding_new_furniture, name='adding_new_furniture'),
]

apps/crawler/urls.py
from django.urls import path
from crawler.views import update_data, update_ldsp


app_name = "crawler"
urlpatterns = [
    path('update_data/', update_data, name='update_data'),
    path('update_ldst/', update_ldsp, name='update_ldst'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from config.views import redirect_main


urlpatterns = [
    path('', redirect_main),
    path('', include('calc.urls')),
    path('', include('crawler.urls')),
    path('blog/', include('blog.urls')),

    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social')),
]

apps/calc/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from config.models import BaseModel


class CalcTag(BaseModel):
    """Модель категорий расчётов"""
    title = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'Тэг расчёта'
        verbose_name_plural = 'Тэги расчётов'

    def __str__(self):
        return self.title


class Calc(BaseModel):
    """Модель расчёта"""
    designer = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.DO_NOTHING)
    tags = models.ForeignKey(CalcTag, blank=True, null=True, default=None, on_delete=models.DO_NOTHING)  # tag
    title = models.CharField('Название расчёта', max_length=128)
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Расчёт'
        verbose_name_plural = 'Расчёты'

    def __str__(self):
        return self.title

    def was_calc_recently(self):  # Можно использоваться для быстрого поиска недавних расчётов
        return self.create_at >= (timezone.now() - datetime.timedelta(day=7))


class Detail(BaseModel):
    """Модель детали в расчёте"""
    calc = models.ForeignKey(Calc, on_delete=models.CASCADE)
    height = models.PositiveIntegerField('Высота')
    width = models.PositiveIntegerField('Ширина')
    nmb = models.PositiveIntegerField('Количество')
    price_material = models.PositiveIntegerField('Цена м2')
    total_price = models.DecimalField('Стоимость', decimal_places=2, max_digits=10, default=0)

    class Meta:
        verbose_name = 'Деталь'
        verbose_name_plural = 'Детали'

    def __str__(self):
        return '{} - {}x{}-{}'.format(self.calc, self.height, self.width, self.nmb)

    def save(self, *args, **kwargs):
        # Автоматический расчёт общей стоимости при сохранении
        self.total_price = int(self.nmb) \
                           * int(self.height) * int(self.width) \
                           * int(self.price_material) \
                           / 10000  # Т.к. в сантиметрах делим на 10000
        super(Detail, self).save(*args, **kwargs)


class CategoryFurniture(BaseModel):
    """Модель категории фурнитуры"""
    title = models.CharField(max_length=100, default=None)

    class Meta:
        verbose_name = 'Категория фурнитуры'
        verbose_name_plural = 'Категории фурнитуры'

    def __str__(self):
        return self.title


class Furniture(BaseModel):
    """Модель фурнитуры"""
    category = models.ForeignKey(CategoryFurniture, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100, default=None)
    article = models.CharField(max_length=50, default=None)
    price = models.DecimalField(decimal_places=2, max_digits=8, default=None)
    price_retail = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True)
    availability = models.CharField('Наличие', max_length=20, null=True, default=None)

    class Meta:
        verbose_name = 'Фурнитура'
        verbose_name_plural = 'Фурнитура'

    def __str__(self) -> str:
        return '%s - %s - %s - %s' % (self.category, self.title[:50], self.price, self.price_retail)


class FurnitureInCalc(BaseModel):
    """Модель фурнитуры в заказе"""
    calc = models.ForeignKey(Calc, on_delete=models.CASCADE)
    furniture = models.ForeignKey(Furniture, null=True, on_delete=models.SET_NULL)
    title = models.CharField('Название', max_length=100)
    article = models.CharField('Артикул', max_length=50, unique=True)
    price = models.DecimalField('Оптовая цена', decimal_places=2, max_digits=8)
    price_retail = models.DecimalField('Розничная цена', decimal_places=2, max_digits=8, default=1)
    availability = models.CharField('Наличие', max_length=20, null=True)
    nmb = models.PositiveIntegerField('Количество')
    total_price = models.DecimalField('Итого', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Фурнитура в расчёте'
        verbose_name_plural = 'Фурнитура в расчёте'

    def __str__(self) -> str:
        return '%s - %s - %s - %s' % (self.calc.title, self.title[:50], self.price, self.price_retail)

    def save(self, *args, **kwargs) -> None:
        # Автоматический расчёт общей стоимости и параметров при добавлении
        if self.furniture is not None:
            self.title = self.furniture.title
            self.article = self.furniture.article
            self.price = self.furniture.price
            self.price_retail = self.furniture.price_retail
            self.availability = self.furniture.availability
        self.total_price = self.nmb * float(self.price_retail)
        super(FurnitureInCalc, self).save(*args, **kwargs)


class Ldstp(BaseModel):
    """Модель ЛДСП для информации о наличии цветов"""
    title = models.CharField(max_length=128)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    availability = models.CharField(max_length=32)

    class Meta:
        verbose_name = 'ЛДСП'
        verbose_name_plural = 'ЛДСП'

    def __str__(self):
        return '%s - %s - %s' % (self.title, self.price, self.availability)


class Comment(BaseModel):
    """Модель комментария к расчёту"""
    calc = models.ForeignKey(Calc, on_delete=models.CASCADE)
    title = models.CharField('Тема', max_length=50)
    text = models.TextField('Текст комментария', max_length=1000)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return '%s - %s' % (self.calc.title, self.title)


class Box(BaseModel):
    pass

apps/calc/forms.py
from django import forms

from calc.models import Calc, Comment, FurnitureInCalc


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["calc"]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }


class CalcForm(forms.ModelForm):
    class Meta:
        model = Calc
        fields = ["title", "tags"]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': forms.Select(attrs={'class': 'form-control'}),
        }


class FurnitureInCalcForm(forms.ModelForm):
    """Форма для добавления фурнитуры не из БД"""
    class Meta:
        model = FurnitureInCalc
        exclude = ["calc", "furniture", "total_price"]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'article': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'price_retail': forms.TextInput(attrs={'class': 'form-control'}),
            'availability': forms.TextInput(attrs={'class': 'form-control'}),
            'nmb': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/calc/views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.http.request import HttpRequest
from django.contrib.auth.decorators import login_required

from calc.models import Calc, Furniture, FurnitureInCalc, Ldstp, Comment, Detail
from calc.forms import CalcForm, CommentForm, FurnitureInCalcForm
from calc.utils import current_furniture_in_calc_and_main_calc_info, current_details_in_calc_and_main_calc_info


def calcs_list(request):
    """Показывает список текущих расчётов"""
    if request.user.is_authenticated:
        if request.user.is_staff:
            calc_list = Calc.objects.order_by('-create_at')[:15]
        else:
            calc_list = Calc.objects.filter(designer=request.user).order_by('-create_at')
    return render(request, 'calc/calc_list.html', locals())


@login_required
def adding_calc(request):
    """Добавляет новый расчёт"""
    if request.POST:
        form = CalcForm(request.POST)
        if form.is_valid():
            obj = Calc.objects.create(designer=request.user, title=form.cleaned_data["title"],
                                      tags=form.cleaned_data["tags"])
            obj.save()
            return HttpResponseRedirect(reverse('calc_details', args=(obj.id,)))
        return render(request, 'calc/adding_calc.html', locals())
    else:
        form = CalcForm()
        return render(request, 'calc/adding_calc.html', locals())


@login_required
def calc_details(request: HttpRequest, calc_id: int):
    """Подробная информация по расчёту
    Инфо по текущим деталям и текущей фурнитуре получаем через Ajax"""
    calc = Calc.objects.get(pk=calc_id)
    if calc.designer != request.user and not request.user.is_staff:
        return HttpResponseRedirect(reverse('calc_list'))
    furniture = Furniture.objects.all()
    standard_furniture = furniture.filter(category_id=1)
    kitchen_furniture = furniture.filter(category_id=2)
    countertops_furniture = furniture.filter(category_id=3)
    silk_and_drying_furniture = furniture.filter(category_id=4)
    lift_and_box_furniture = furniture.filter(category_id=5)
    mensolo_hangers_legs_furniture = furniture.filter(category_id=6)
    wardrobe_furniture = furniture.filter(category_id=7)
    handle_furniture = furniture.filter(category_id=8)
    ldsp_list = Ldstp.objects.all()
    latest_comment = Comment.objects.filter(calc_id=calc_id).order_by('-id')
    return render(request, 'calc/calc_details.html', locals())


def crud_detail(request):
    """Создание или удаление в случае флага is_delete деталей в расчёте"""
    data = request.POST
    detail_id = data.get("detail_id")
    calc_id = data.get("calc_id")
    is_delete = data.get("is_delete")
    height = data.get("height")
    width = data.get("width")
    nmb = int(data.get("nmb"))
    price_material = data.get("price_material")
    if is_delete == "true":
        obj = Detail.objects.get(id=detail_id)
        obj.delete()
    elif nmb > 0:
        if int(detail_id) == 0:
            new_detail = Detail.objects.create(calc_id=calc_id, height=height,
                                               width=width, nmb=nmb, price_material=price_material)
            new_detail.save(force_update=True)
        else:
            new_obj = Detail.objects.get(id=detail_id)
            new_obj.nmb = int(nmb)
            new_obj.save(force_update=True)
    return JsonResponse(current_details_in_calc_and_main_calc_info(calc_id=int(calc_id)))


def crud_furniture(request):
    """Создание или удаление в случае флага is_delete деталей в расчёте"""
    data = request.POST
    furniture_id = data.get("furniture_id")
    calc_id = data.get("calc_id")
    is_delete = data.get("is_delete")
    nmb = int(data.get("nmb"))
    if is_delete == "true":
        obj = FurnitureInCalc.objects.get(calc_id=calc_id, id=furniture_id)
        obj.delete()
    elif nmb > 0:
        new_obj, created = FurnitureInCalc.objects.get_or_create(calc_id=calc_id,
                                                                 furniture_id=furniture_id, defaults={"nmb": nmb})
        if not created:
            new_obj.nmb = int(nmb)
            new_obj.save(force_update=True)
    return JsonResponse(current_furniture_in_calc_and_main_calc_info(calc_id=int(calc_id)))


def leave_comment(request, calc_id):
    """Форма для добавления нового комментария"""
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = Comment.objects.create(calc_id=calc_id,
                                         title=form.cleaned_data["title"],
                                         text=form.cleaned_data["text"])
            obj.save()
            return HttpResponseRedirect(reverse('calc_details', args=(calc_id,)))
        return render(request, 'calc/leave_comment.html', locals())
    else:
        form = CommentForm()
        return render(request, 'calc/leave_comment.html', locals())


def adding_new_furniture(request, calc_id):
    """Форма для добавления новой фурнитуры не из Базы данных"""
    if request.POST:
        form = FurnitureInCalcForm(request.POST)
        if form.is_valid():
            obj = FurnitureInCalc.objects.create(
                calc_id=calc_id,
                title=form.cleaned_data["title"],
                article=form.cleaned_data["article"],
                price=form.cleaned_data["price"],
                price_retail=form.cleaned_data["price_retail"],
                availability=form.cleaned_data["availability"],
                nmb=form.cleaned_data["nmb"])
            obj.save()
            return HttpResponseRedirect(reverse('calc_details', args=(calc_id,)))
        return render(request, 'calc/adding_new_furniture.html', locals())
    else:
        form = FurnitureInCalcForm()
        return render(request, 'calc/adding_new_furniture.html', locals())

templates/calc/adding_calc.html
{% extends 'base.html' %}

{% block title%} Создать новый расчёт {% endblock %}

{% block main %} 
    <form action="{% url 'adding_calc'  %}" method="POST">
        {%csrf_token%}
        {% for field in form %}
        <div class="form-group">
            {% if field.errors %}
            <div class="alert alert-danger">
                {{field.errors}}
            </div>
            {% endif %}
            {{field.label}}
            <br>
            {{field}}
        </div>
        {%endfor%}
        <br>
        <button type="submit" class="btn btn-primary">Создать расчёт</button>
    </form>
{% endblock %}

templates/calc/adding_new_furniture.html
{% extends 'base.html' %}

{% block title%} Добавить новую фурнитуру {% endblock %}

{% block main %}
    <form action="{% url 'adding_new_furniture' calc_id  %}" method="POST">
        {%csrf_token%}
        {% for field in form %}
        <div class="form-group">
            <br>
            {% if field.errors %}
            <div class="alert alert-danger">
                {{field.label}} {{field.errors}}
            </div>
            {% endif %}
            {{field.label}}
            <br>
            {{field}}
        </div>
        {%endfor%} 
        <br>
        <button class="btn btn-primary" type="submit">Добавить фурнитуру</button>
    </form>
{% endblock %}

templates/calc/calc_list.html
{% extends 'base.html' %}

{% block title%} Список расчётов {% endblock %}

{% block main %}
{% if user.is_authenticated %}
    <p> Доброго времени суток {{ user.username }}
     <a class="btn btn-secondary" href="{% url 'password_change' %}">Изменить пароль</a>
     <a class="btn btn-primary" href="{% url 'logout' %}?next={{request.path}}">Выйти</a> 
    </p>
    
    <h2 class="mt-3">Расчёты:</h2>
    {% if calc_list %}
    <table class="table caption-top table-hover">
    <caption>Таблица расчётов</caption>
    <thead class="table-secondary">
        <tr>
        <th scope="col">#id</th>
        <th scope="col">Дизайнер</th>
        <th scope="col">Название расчёта</th>
        <th scope="col">Тэги</th>
        <th scope="col">Дата расчёта</th>
        </tr>
    </thead>
    <tbody>
        {% for calc in calc_list %}
            <tr>
                <th scope="row">{{calc.id}}</th>
                <td>{{calc.designer}}</td>
                <td><a href="{% url 'calc_details' calc.id %}">{{calc.title}}</a></td>
                <td>{{calc.tags}}</td>
                <td>{{calc.create_at}}</td>
            </tr>
        {% endfor %} 
    </tbody>
    </table>
    <a type="button" class="btn btn-success mt-4 mb-4" href="{% url 'adding_calc' %}">Создать расчёт</a>   
    {% else %}
        <h2>Нет расчётов</h2>
        <a type="button" class="btn btn-success mt-4 mb-4" href="{% url 'adding_calc' %}">Создать расчёт</a>
    {% endif %}  
{% else %}
    <h2>Авторизуйтесь чтобы увидеть расчёты</h2>
    <a class="btn btn-primary" href="{% url 'login' %}?next={{request.path}}">Войти</a>
    <a class="btn btn-secondary" href="{% url 'password_reset' %}">Забыли пароль?</a>
{% endif %}

<form class="update-furniture-data mt-4 mb-4" action="{% url 'crawler:update_data' %}">{% csrf_token %}
<button type=submit class="btn btn-primary">Обновить данные МакМарт(12мин)</button>
</form>
<form class="update-furniture-data mt-4 mb-4" action="{% url 'crawler:update_ldst' %}">{% csrf_token %}
<button type=submit class="btn btn-primary">Обновить данные ЛДСП(1мин)</button>
</form>

{% endblock %}

templates/calc/leave_comment.html
{% extends 'base.html' %}

{% block title%} Добавить новый комментарий {% endblock %}

{% block main %}
    <form action="{% url 'leave_comment' calc_id  %}" method="POST">
        {%csrf_token%}
        {% for field in form %}
        <div class="form-group">
            {% if field.errors %}
            <div class="alert alert-danger">
                {{field.errors}}
            </div>
            {% endif %}
            {{field.label}}
            <br>
            {{field}}
        </div>
        {%endfor%} 
        <br>
        <button class="btn btn-primary" type="submit">Добавить комментарий</button>
    </form>
{% endblock %}